# This is a basic workflow to help you get started with Actions

name: Test Workflow Parameters

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      inputs:
        CheckInResults:
          description: 'Should results be checked into get'     
          required: true
          default: 'yes'
  
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "fetch"
  fetch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run a shell script which fetches the data, and builds the website.
        run: |
          echo The parameter value was ${{ github.event.inputs.CheckInResults }}
          if [ ${{ github.event.inputs.CheckInResults }} = "yes" ]; then
            echo "Would run git"
          else
            echo "Would not run git"
          fi

