# This is a basic workflow to help you get started with Actions

name: Test Workflow Parameters

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      inputs:
        CheckInResults:
          description: 'Should results be checked into git'     
          required: true
          default: 'yes'
  
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '36 1 1 1 *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "fetch"
  fetch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      run_git: ${{ github.event.inputs.CheckInResults }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set run_git environment variable
        if: env.run_git == null
        run: echo "run_git=yes" >> $GITHUB_ENV

      - name: Run a shell script which fetches the data, and builds the website.
        run: echo "run_git=$run_git"
    
